/*
 * App URI: loadmask
 * Source Location: loadmask.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("loadmask", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["cl-loadmask", "cl-overlay"]);
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			group_1.style.setClasses(["cl-dialog"]);
			group_1.style.css({
				"border-right-style" : "solid",
				"border-top-width" : "2px",
				"border-bottom-color" : "#959697",
				"border-right-width" : "2px",
				"border-left-color" : "#959697",
				"border-right-color" : "#959697",
				"border-left-width" : "2px",
				"border-top-style" : "solid",
				"background-color" : "#ffffff",
				"border-left-style" : "solid",
				"border-bottom-width" : "2px",
				"border-top-color" : "#959697",
				"border-bottom-style" : "solid"
			});
			// Layout
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var output_1 = new cpr.controls.Output();
				output_1.value = "3~4분이상 소요됩니다.";
				output_1.style.css({
					"padding" : "7px 0px 0px 40px",
					"background-repeat" : "no-repeat",
					"font-weight" : "bold",
					"background-image" : "url('image/loader.gif')"
				});
				container.addChild(output_1, {
					"right": "72px",
					"left": "72px",
					"height": "38px",
					"top": "calc(50% - 19px)"
				});
			})(group_1);
			container.addChild(group_1, {
				"width": "400px",
				"height": "200px",
				"left": "calc(50% - 200px)",
				"top": "calc(50% - 100px)"
			});
		}
	});
	app.title = "loadmask";
	cpr.core.Platform.INSTANCE.register(app);
})();
