/*
 * App URI: tester/tester
 * Source Location: tester/tester.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("tester/tester", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * tester.js
			 * Created at 2019. 12. 2. 오후 5:46:02.
			 *
			 * @author HANS
			 ************************************************/
			 //var util = createCommonUtil();
			/*
			 * "Button" 버튼(btn2)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn2Click(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var btn2 = e.control;
				
			var showConstraint = {
						"position" : "absolute",
						"top" : "0",
						"bottom" : "0",
						"left" : "0",
						"right" : "0",
						"z-index" : "1000"
				};
				var udcs = new udc.loadmask("loadmasks");
				app.getContainer().addChild(udcs, showConstraint);
				
				app.lookup("sms1").send();
			}
			
			
			/*
			 * 서브미션에서 submit-success 이벤트 발생 시 호출.
			 * 통신이 성공하면 발생합니다.
			 */
			function onSms1SubmitSuccess(/* cpr.events.CSubmissionEvent */ e){
				/** 
				 * @type cpr.protocols.Submission
				 */
				var sms1 = e.control;
				
				app.getContainer().removeChild(app.lookup("loadmasks"));
			};
			// End - User Script
			
			// Header
			app.declareAppProperty("dialog", null);
			var dataSet_1 = new cpr.data.DataSet("dsMst");
			dataSet_1.parseData({
				"columns" : [
					{"name": "column1"},
					{
						"name": "column2",
						"dataType": "number"
					},
					{
						"name": "column3",
						"dataType": "number"
					},
					{
						"name": "column4",
						"dataType": "number"
					},
					{"name": "column5"},
					{"name": "column6"},
					{"name": "column7"},
					{"name": "column8"},
					{"name": "column9"},
					{"name": "column10"},
					{"name": "column11"},
					{
						"name": "level",
						"dataType": "number"
					}
				]
			});
			app.register(dataSet_1);
			
			var dataSet_2 = new cpr.data.DataSet("dsDtl");
			dataSet_2.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"},
					{"name": "column6"},
					{"name": "column7"},
					{"name": "column8"},
					{"name": "column9"},
					{"name": "column10"},
					{"name": "column11"},
					{"name": "column12"},
					{"name": "column13"},
					{"name": "column14"},
					{"name": "column15"},
					{"name": "column16"},
					{"name": "column17"}
				]
			});
			app.register(dataSet_2);
			
			var dataSet_3 = new cpr.data.DataSet("dsVoucher");
			dataSet_3.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"},
					{"name": "column6"}
				]
			});
			app.register(dataSet_3);
			
			var dataSet_4 = new cpr.data.DataSet("dsVoucherCard");
			dataSet_4.parseData({
				"columns": [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"},
					{
						"name": "column6",
						"dataType": "number"
					}
				],
				"rows": [
					{"column1": "column11", "column2": "column21", "column3": "column31", "column4": "column41", "column5": "column51", "column6": "1"},
					{"column1": "column12", "column2": "column22", "column3": "column32", "column4": "column42", "column5": "column52", "column6": "2"},
					{"column1": "column13", "column2": "column23", "column3": "column33", "column4": "column43", "column5": "column53", "column6": "3"},
					{"column1": "column14", "column2": "column24", "column3": "column34", "column4": "column44", "column5": "column54", "column6": "4"},
					{"column1": "column15", "column2": "column25", "column3": "column35", "column4": "column45", "column5": "column55", "column6": "5"}
				]
			});
			app.register(dataSet_4);
			
			var dataSet_5 = new cpr.data.DataSet("dsRegularCheck");
			dataSet_5.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"},
					{"name": "column6"},
					{"name": "column7"},
					{"name": "column8"},
					{"name": "column9"},
					{"name": "column10"},
					{"name": "column11"}
				]
			});
			app.register(dataSet_5);
			
			var dataSet_6 = new cpr.data.DataSet("dsAlwaysCheck");
			dataSet_6.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"},
					{"name": "column6"},
					{"name": "column7"},
					{"name": "column8"},
					{"name": "column9"},
					{"name": "column10"},
					{"name": "column11"}
				]
			});
			app.register(dataSet_6);
			
			var dataSet_7 = new cpr.data.DataSet("ds1");
			dataSet_7.parseData({
				"columns": [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{
						"name": "level",
						"dataType": "number"
					}
				],
				"rows": [
					{"column1": "column11", "column2": "column21", "column3": "column31", "level": "1"},
					{"column1": "column12", "column2": "column22", "column3": "column32", "level": "1"},
					{"column1": "column13", "column2": "column23", "column3": "column33", "level": "1"},
					{"column1": "column14", "column2": "column24", "column3": "column34", "level": "1"},
					{"column1": "column15", "column2": "column25", "column3": "column35", "level": "2"},
					{"column1": "column16", "column2": "column26", "column3": "column36", "level": "2"},
					{"column1": "column17", "column2": "column27", "column3": "column37", "level": "3"},
					{"column1": "column18", "column2": "column28", "column3": "column38", "level": "1"},
					{"column1": "column19", "column2": "column29", "column3": "column39", "level": "2"}
				]
			});
			app.register(dataSet_7);
			var submission_1 = new cpr.protocols.Submission("sms1");
			submission_1.action = "datas/dataMst.json";
			submission_1.addResponseData(dataSet_1, false);
			if(typeof onSms1BeforeSubmit == "function") {
				submission_1.addEventListener("before-submit", onSms1BeforeSubmit);
			}
			if(typeof onSms1SubmitDone == "function") {
				submission_1.addEventListener("submit-done", onSms1SubmitDone);
			}
			if(typeof onSms1SubmitSuccess == "function") {
				submission_1.addEventListener("submit-success", onSms1SubmitSuccess);
			}
			app.register(submission_1);
			
			var submission_2 = new cpr.protocols.Submission("sms2");
			submission_2.action = "datas/dataDtl.json";
			submission_2.addResponseData(dataSet_2, false);
			app.register(submission_2);
			
			var submission_3 = new cpr.protocols.Submission("sms3");
			submission_3.action = "datas/dataVoucher.json";
			submission_3.addResponseData(dataSet_3, false);
			submission_3.addResponseData(dataSet_4, false);
			submission_3.addResponseData(dataSet_5, false);
			submission_3.addResponseData(dataSet_6, false);
			app.register(submission_3);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("grp1");
			group_1.style.css({
				"border-right-style" : "solid",
				"border-top-width" : "1px",
				"border-bottom-color" : "black",
				"border-left-style" : "solid",
				"border-right-width" : "1px",
				"border-bottom-width" : "1px",
				"border-left-color" : "black",
				"border-top-color" : "black",
				"border-bottom-style" : "solid",
				"border-right-color" : "black",
				"border-left-width" : "1px",
				"border-top-style" : "solid"
			});
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			group_1.setLayout(verticalLayout_1);
			(function(container){
				var button_1 = new cpr.controls.Button("btn2");
				button_1.value = "서브미션 전송 버튼";
				if(typeof onBtn2Click == "function") {
					button_1.addEventListener("click", onBtn2Click);
				}
				container.addChild(button_1, {
					"width": "100px",
					"height": "25px"
				});
				var button_2 = new cpr.controls.Button("btn4");
				button_2.value = "Button";
				if(typeof onBtn4Click == "function") {
					button_2.addEventListener("click", onBtn4Click);
				}
				container.addChild(button_2, {
					"width": "60px",
					"height": "44px"
				});
				var button_3 = new cpr.controls.Button("btn3");
				button_3.value = "Button";
				container.addChild(button_3, {
					"width": "60px",
					"height": "168px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "252px",
				"left": "116px",
				"width": "400px",
				"height": "300px"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "tester";
	cpr.core.Platform.INSTANCE.register(app);
})();
